const brand=()=>String(process.env.BRAND_NAME||"DENFIT").trim();
const logo=()=>String(process.env.BRAND_LOGO_URL||"https://www.denfit.shop/denfit-logo.svg");
const esc=(v)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const formatMoney=(amount,currency="PKR")=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:currency==="PKR"?0:2}).format(Number(amount||0));
const shell=({eyebrow,title,intro,body,status,ctaLabel,ctaUrl})=>{
 const accent=status==="Cancelled"?"#b42318":status==="Delivered"||status==="Confirmed"?"#1f7a4d":"#111111";
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{margin:0;background:#f4f1ec;color:#111;font-family:Arial,Helvetica,sans-serif}.wrap{max-width:680px;margin:0 auto;background:#fff}.head{padding:34px 42px 28px;border-bottom:1px solid #e8e3dc;background:#fff}.logo{max-width:150px;max-height:58px;display:block}.ey{font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#777;margin:26px 0 10px}.title{font-family:Georgia,serif;font-size:38px;line-height:1.1;margin:0;color:#111}.rule{height:3px;width:54px;background:${accent};margin:24px 0}.content{padding:12px 42px 42px;font-size:16px;line-height:1.75;color:#444}.card{margin:28px 0;padding:24px;background:#faf9f7;border:1px solid #ebe7e1}.cta{display:inline-block;margin-top:18px;padding:14px 24px;background:#111;color:#fff!important;text-decoration:none;font-size:12px;letter-spacing:1.6px;text-transform:uppercase}.foot{padding:30px 42px;background:#111;color:#f4f1ec;font-size:12px;line-height:1.7}.foot a{color:#fff;text-decoration:none}</style></head><body><div class="wrap"><header class="head"><img class="logo" src="${logo()}" alt="${esc(brand())}" onerror="this.style.display='none'"><div class="ey">${esc(eyebrow||brand())}</div><h1 class="title">${esc(title)}</h1><div class="rule"></div></header><main class="content"><p>${esc(intro)}</p>${body||""}${ctaLabel&&ctaUrl?`<a class="cta" href="${ctaUrl}">${esc(ctaLabel)}</a>`:""}</main><footer class="foot"><strong>${esc(brand())}</strong><br>Thoughtfully designed updates for your account and orders.<br><br><a href="https://www.denfit.shop">Visit the store</a></footer></div></body></html>`;
};
export const getSignupEmail=(name)=>shell({eyebrow:"Welcome",title:"Your account is ready",intro:`Hello ${name}, welcome to ${brand()}. Your account is ready whenever you are.`,body:"<div class='card'>Discover new arrivals, saved favourites and a smoother checkout from one place.</div>",ctaLabel:"Explore the collection",ctaUrl:"https://www.denfit.shop/products"});
export const getLoginEmail=(name)=>shell({eyebrow:"Account activity",title:"You signed in",intro:`Hello ${name}, we noticed a successful sign-in to your account.`,body:"<div class='card'>If this was you, no action is needed. If not, reset your password immediately.</div>",ctaLabel:"Open my account",ctaUrl:"https://www.denfit.shop/profile"});
export const getOTPEmail=(code)=>shell({eyebrow:"Password reset",title:"Your verification code",intro:"Use the code below to continue resetting your password.",body:`<div class='card' style='font-family:Georgia,serif;font-size:34px;letter-spacing:8px;color:#111;text-align:center'>${esc(code)}</div><p>This code expires in 10 minutes.</p>`});
export const getOrderEmail=(name,orderId,total,currency="PKR")=>shell({eyebrow:"Order confirmed",title:"We have your order",status:"Confirmed",intro:`Thank you, ${name}. Your order is confirmed and is now being prepared.`,body:`<div class='card'><strong>Order</strong><br>#${esc(orderId)}<br><br><strong>Total</strong><br>${esc(formatMoney(total,currency))}</div>`,ctaLabel:"View my account",ctaUrl:"https://www.denfit.shop/profile"});
export const getStatusEmail=(name,orderId,status,tracking,total,currency="PKR")=>shell({eyebrow:"Order update",title:`Order ${status}`,status,intro:`Hello ${name}, your order status has been updated to ${status}.`,body:`<div class='card'><strong>Order</strong><br>#${esc(orderId)}${tracking?`<br><br><strong>Tracking</strong><br>${esc(tracking)}`:""}<br><br><strong>Total</strong><br>${esc(formatMoney(total,currency))}</div>`,ctaLabel:"View order",ctaUrl:"https://www.denfit.shop/profile"});
export const getShippedEmail=(name,orderId)=>getStatusEmail(name,orderId,"Shipped","",0);
export const getDeliveredEmail=(name,orderId)=>getStatusEmail(name,orderId,"Delivered","",0);
export const getAbandonedCartEmail=(name)=>shell({eyebrow:"Your selection",title:"Still thinking it over?",intro:`Hello ${name}, the pieces in your bag are still waiting for you.`,body:"<div class='card'>Availability can change as the collection moves. Return when you are ready.</div>",ctaLabel:"Return to my bag",ctaUrl:"https://www.denfit.shop/cart"});
export const getWishlistEmail=(name)=>shell({eyebrow:"Saved pieces",title:"Your favourites are waiting",intro:`Hello ${name}, revisit the pieces you saved and continue your selection.`,ctaLabel:"Open wishlist",ctaUrl:"https://www.denfit.shop/wishlist"});
