import { ATELIER_CONFIG } from './AtelierAesthetics.js';

const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as any)[c]);
const site=()=>String(ATELIER_CONFIG.frontendUrl||'https://www.denfit.shop').replace(/\/$/,'');
const link=(path:string)=>/^https?:\/\//i.test(path)?path:`${site()}${path.startsWith('/')?path:`/${path}`}`;

export const atelierBase=(content:string,previewText:string,themeColor='#C7A15A')=>{
 const brand=esc(ATELIER_CONFIG.brandName||'DENFIT');
 const logo=esc(ATELIER_CONFIG.logoUrl||`${site()}/denfit-logo.svg`);
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>${brand}</title><style>@media(max-width:680px){.shell{width:100%!important;border-radius:0!important}.pad{padding:22px 16px!important}.hero-title{font-size:30px!important}.hero-copy{font-size:13px!important}.two{display:block!important;width:100%!important}.nav{white-space:normal!important}.product{width:50%!important}.hide-mobile{display:none!important}}</style></head><body style="margin:0;padding:0;background:#EEECE7;font-family:Arial,Helvetica,sans-serif;color:#14181F;-webkit-text-size-adjust:100%"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${esc(previewText)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#EEECE7;padding:24px 8px"><tr><td align="center"><table role="presentation" class="shell" width="700" cellspacing="0" cellpadding="0" border="0" style="max-width:700px;width:100%;background:#FFFFFF;border:1px solid #DEDCD6;border-radius:22px;overflow:hidden;box-shadow:0 12px 40px rgba(15,20,25,.08)">
<tr><td style="height:4px;background:${themeColor};font-size:0;line-height:0">&nbsp;</td></tr>
<tr><td style="padding:22px 28px 17px;background:#FCFBF8;border-bottom:1px solid #E9E7E1"><table role="presentation" width="100%"><tr><td><a href="${link('/')}" style="text-decoration:none"><img src="${logo}" alt="${brand}" width="142" style="display:block;width:142px;max-height:62px;object-fit:contain"></a></td><td align="right" style="font-size:10px;letter-spacing:.22em;color:#626B77;white-space:nowrap">STYLE / QUALITY / YOU</td></tr></table><div class="nav" style="margin-top:15px;font-size:10px;letter-spacing:.02em"><a href="${link('/products')}" style="color:#4D5662;text-decoration:none;margin-right:18px">Shop Now</a><a href="${link('/profile')}" style="color:#4D5662;text-decoration:none;margin-right:18px">Track Order</a><a href="${link('/support')}" style="color:#4D5662;text-decoration:none;margin-right:18px">Help</a><a href="${link('/contact')}" style="color:#4D5662;text-decoration:none">Contact</a></div></td></tr>
<tr><td class="pad" style="padding:30px;background:#FFFFFF">${content}</td></tr>
<tr><td style="padding:17px 22px;background:#FAF9F6;border-top:1px solid #ECEAE4;text-align:center"><table role="presentation" width="100%"><tr><td width="33%" style="font-size:10px;color:#1F2731"><b style="color:#9A6D2E">◇</b><br><b>Premium Quality</b><br><span style="color:#7B8490">Selected with care</span></td><td width="34%" style="font-size:10px;color:#1F2731;border-left:1px solid #E3E0D9;border-right:1px solid #E3E0D9"><b style="color:#9A6D2E">◇</b><br><b>Secure Checkout</b><br><span style="color:#7B8490">Safe & encrypted</span></td><td width="33%" style="font-size:10px;color:#1F2731"><b style="color:#9A6D2E">◇</b><br><b>Dedicated Support</b><br><span style="color:#7B8490">Here when needed</span></td></tr></table></td></tr>
<tr><td style="padding:30px 24px;background:#090D12;text-align:center"><a href="${link('/')}" style="text-decoration:none"><img src="${logo}" alt="${brand}" width="112" style="display:block;margin:0 auto;width:112px;max-height:55px;object-fit:contain"></a><div style="font:14px Georgia,serif;color:#E8D6B4;margin-top:9px;font-style:italic">More Style, More You ♡</div><div style="margin-top:17px"><a href="${link('/products')}" style="color:#E1E5EA;text-decoration:none;font-size:10px">Shop</a><span style="color:#555D66;padding:0 8px">|</span><a href="${link('/about')}" style="color:#E1E5EA;text-decoration:none;font-size:10px">About Us</a><span style="color:#555D66;padding:0 8px">|</span><a href="${link('/support')}" style="color:#E1E5EA;text-decoration:none;font-size:10px">Help</a><span style="color:#555D66;padding:0 8px">|</span><a href="${link('/contact')}" style="color:#E1E5EA;text-decoration:none;font-size:10px">Contact</a></div><div style="margin-top:15px;font-size:9px;color:#89919B">${esc(ATELIER_CONFIG.supportEmail||'support@denfit.shop')}</div><div style="margin-top:13px;font-size:9px;color:#69727D">© ${new Date().getFullYear()} ${brand}. All rights reserved.</div><div style="margin-top:7px"><a href="${link('/support?tab=privacy')}" style="color:#69727D;text-decoration:none;font-size:9px">Privacy</a><span style="color:#3E444B;padding:0 6px">·</span><a href="${link('/support?tab=returns')}" style="color:#69727D;text-decoration:none;font-size:9px">Returns</a><span style="color:#3E444B;padding:0 6px">·</span><a href="${link('/support?tab=terms')}" style="color:#69727D;text-decoration:none;font-size:9px">Terms</a></div></td></tr>
</table></td></tr></table></body></html>`;
};
