import { atelierBase } from './AtelierBase.js';
import { ATELIER_THEMES, ATELIER_CONFIG } from './AtelierAesthetics.js';
import { renderButton, renderLine, renderTrendingGrid, renderOrderItems, renderOrderSummary } from './AtelierComponents.js';
import { formatCurrency } from '../config/brand.js';

const safe = (v: any) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as any)[c]);
const intro = (eyebrow: string, heading: string, body: string, accent = '#D4AF37') => `<div style="font-size:10px;color:${accent};letter-spacing:.28em;margin-bottom:16px;text-transform:uppercase;font-weight:700;">${safe(eyebrow)}</div><h2 style="color:#0F0F0F;font-family:Georgia,'Times New Roman',serif;font-size:31px;font-weight:400;margin:0 0 18px;line-height:1.25;">${heading}</h2><p style="color:#555;line-height:1.8;font-size:15px;margin:0;">${body}</p>`;

export const getSignupEmail = (name: string, liveProducts: any[] = [], currency = 'USD') => { const theme = ATELIER_THEMES.signup; const content = `${intro('Welcome', `Welcome to ${safe(ATELIER_CONFIG.brandName)}, <b>${safe(name)}</b>`, `Your account is ready. Explore the live collection, save favourites and manage your orders from one place.`, theme.accent)}${renderLine()}${renderButton('Open Your Account','/profile',theme.primary)}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `Welcome to ${ATELIER_CONFIG.brandName}`, theme.primary); };

export const getLoginEmail = (name: string, liveProducts: any[] = [], currency = 'USD') => { const theme = ATELIER_THEMES.login; const content = `${intro('Account Security', `Welcome back, <b>${safe(name)}</b>`, `A successful sign-in to your ${safe(ATELIER_CONFIG.brandName)} account was detected at <b>${new Date().toLocaleTimeString()}</b>.`)}<p style="color:#888;font-size:13px;line-height:1.7;margin-top:16px;">If you did not make this sign-in, please secure your account and contact support.</p>${renderLine()}${renderButton('Open Your Account','/profile',theme.primary)}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Sign-in notification`, theme.primary); };

export const getOrderEmail = (name: string, orderId: string, total: string, liveProducts: any[] = [], order: any = {}) => { const theme = ATELIER_THEMES.order; const currency = String(order.currency || liveProducts.find((p:any)=>p?.currency)?.currency || 'USD').toUpperCase(); const totalNumber = Number(order.totalAmount ?? total ?? 0); const content = `${intro('Order Confirmed', `Thank you, <b>${safe(name)}</b>`, `Your order with ${safe(ATELIER_CONFIG.brandName)} has been confirmed. We are preparing your pieces with care.` , theme.accent)}${renderLine()}<div style="padding:18px 20px;background:#FBF8F1;border:1px solid #E9E1D2;"><div style="font-size:10px;color:#888;text-transform:uppercase;letter-spacing:.18em;">Order Number</div><div style="font-size:17px;font-weight:700;margin-top:6px;">#${safe(orderId)}</div><div style="font-size:12px;color:#777;margin-top:10px;">Payment: ${safe(order.paymentMethod || 'Order payment')}</div></div>${renderOrderItems(order.items || [], currency)}${renderOrderSummary({ subtotal: order.subtotal ?? totalNumber, discountAmount: order.discountAmount, discountCode: order.discountCode, shippingCost: order.shippingCost, totalAmount: totalNumber }, currency)}${renderLine()}${renderButton('Track Your Order','/profile',theme.primary)}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Order confirmed`, theme.primary); };

export const getAbandonedCartEmail = (name: string, liveProducts: any[] = [], currency = 'USD') => { const theme = ATELIER_THEMES.cart; const content = `${intro('Your Selection', `Your selection is still waiting`, `Hi <b>${safe(name)}</b>, the pieces you selected are still in your cart. Return whenever you are ready to complete your purchase.`)}${renderLine()}${renderButton('Return to Cart','/cart',theme.primary)}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Your selection awaits`, theme.primary); };

export const getOTPEmail = (otp: string) => { const theme = ATELIER_THEMES.reset; const content = `${intro('Password Reset', `Reset your password`, `Use the secure verification code below to continue resetting your ${safe(ATELIER_CONFIG.brandName)} account.`)}<div style="background:#FBF8F1;padding:24px;font-size:36px;letter-spacing:.42em;color:#0F0F0F;margin:26px 0;border:1px solid #D4AF37;text-align:center;font-weight:700;">${safe(otp)}</div><p style="font-size:12px;color:#999;text-align:center;margin:0;">This code expires in 10 minutes.</p>${renderLine()}${renderButton('Return to Login','/auth','#0A0A0A')}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Password reset`, theme.primary); };

export const getWishlistEmail = (name: string, liveProducts: any[] = [], currency = 'USD') => { const content = `${intro('Wishlist', `Your saved pieces are waiting`, `Hi <b>${safe(name)}</b>, revisit the pieces you saved and discover what is trending now.`)}${renderLine()}${renderButton('View Wishlist','/wishlist','#0A0A0A')}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Wishlist`, '#0A0A0A'); };

export const getPackedEmail = (name: string, orderId: string, liveProducts: any[] = [], currency = 'USD') => { const theme = ATELIER_THEMES.order; const content = `${intro('Order Update', `Your order is packed`, `Hi <b>${safe(name)}</b>, order <b>#${safe(orderId)}</b> has been carefully packed and is ready for dispatch.`)}${renderLine()}${renderButton('View Order','/profile',theme.primary)}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Order packed`, theme.primary); };

export const getShippedEmail = (name: string, orderId: string, liveProducts: any[] = [], currency = 'USD') => { const theme = ATELIER_THEMES.signup; const content = `${intro('Order Update', `Your order is on the way`, `Hi <b>${safe(name)}</b>, order <b>#${safe(orderId)}</b> has been dispatched and is now in transit.`)}${renderLine()}${renderButton('Track Your Order','/profile',theme.primary)}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Order in transit`, theme.primary); };

export const getDeliveredEmail = (name: string, orderId: string, liveProducts: any[] = [], currency = 'USD') => { const theme = ATELIER_THEMES.order; const content = `${intro('Delivery Update', `Your order has arrived`, `Hi <b>${safe(name)}</b>, order <b>#${safe(orderId)}</b> has been successfully delivered.`)}${renderLine()}${renderButton('Open Your Account','/profile','#0A0A0A')}${renderTrendingGrid(liveProducts, currency)}`; return atelierBase(content, `${ATELIER_CONFIG.brandName} | Delivery confirmed`, theme.primary); };
