const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const base=()=>String(process.env.FRONTEND_URL||process.env.SITE_URL||"https://www.denfit.shop").replace(/\/$/,"");
const brand=()=>String(process.env.BRAND_NAME||"DENFIT").trim();
const logo=()=>String(process.env.BRAND_LOGO_URL||`${base()}/denfit-logo.svg`);

const money=(amount,currency="USD")=>{
  try{return new Intl.NumberFormat("en-US",{style:"currency",currency:String(currency||"USD").toUpperCase(),maximumFractionDigits:String(currency).toUpperCase()==="PKR"?0:2}).format(Number(amount||0));}
  catch{return String(amount||0);}
};

const productGrid=(products=[],currency="USD")=>{
  const rows=Array.isArray(products)?products.filter(Boolean).slice(0,3):[];
  if(!rows.length)return "";
  return `<section style="padding:28px 0 0"><div style="font:600 11px Arial,sans-serif;letter-spacing:2px;text-transform:uppercase;color:#152238;text-align:center">Selected for you</div><h2 style="font:400 26px Georgia,serif;margin:10px 0 20px;color:#0b0f16;text-align:center">Trending masterpieces</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>${rows.map((p)=>{const id=esc(p.id||p._id||"");const title=esc(p.name||p.title||"Collection piece");const raw=String(p.image||p.images?.[0]||"");const img=/^https?:\/\//i.test(raw)?raw:raw?`${base()}${raw.startsWith("/")?"":"/"}${raw}`:"";return `<td width="${Math.floor(100/rows.length)}%" style="padding:0 5px 14px;vertical-align:top"><a href="${base()}/product/${id}" style="text-decoration:none;color:#111827;display:block">${img?`<img src="${esc(img)}" alt="${title}" width="100%" style="display:block;width:100%;height:170px;object-fit:cover;background:#f3f4f6;border:1px solid #e5e7eb">`:""}<div style="font:600 12px Arial,sans-serif;line-height:1.45;margin-top:10px">${title}</div><div style="font:12px Arial,sans-serif;color:#334155;margin-top:5px">${money(p.price,currency)}</div></a></td>`;}).join("")}</tr></table></section>`;
};

export const getPromotionalEmail=(name,offerCode,liveProducts=[],currency="USD")=>{
 const code=String(offerCode||"").trim();
 const offer=code?`<div style="margin:28px 0;padding:20px;background:#f7f8fa;border:1px solid #d9dee7;text-align:center"><div style="font:600 10px Arial,sans-serif;letter-spacing:2px;text-transform:uppercase;color:#475569">Private offer</div><div style="font:700 22px Arial,sans-serif;letter-spacing:3px;color:#111827;margin-top:9px">${esc(code)}</div></div>`:"";
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(brand())}</title></head><body style="margin:0;background:#f2f4f7;color:#111827;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden">A private invitation from ${esc(brand())}.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" style="padding:28px 8px"><table role="presentation" width="680" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:680px;background:#fff;border:1px solid #dfe3ea"><tr><td style="padding:28px 36px;background:#0b1220;text-align:center"><a href="${base()}" style="text-decoration:none"><img src="${esc(logo())}" alt="${esc(brand())}" width="155" style="display:block;margin:0 auto;max-width:155px;height:auto;max-height:72px;object-fit:contain"><div style="margin-top:13px;font:600 10px Arial,sans-serif;letter-spacing:3px;text-transform:uppercase;color:#dbe4f0">Private collection</div></a></td></tr><tr><td style="padding:46px 40px 36px"><div style="font:600 10px Arial,sans-serif;letter-spacing:2.4px;text-transform:uppercase;color:#475569">Private invitation</div><h1 style="font:400 38px Georgia,'Times New Roman',serif;line-height:1.15;color:#0b0f16;margin:16px 0">A curated selection for ${esc(name||"you")}</h1><div style="width:54px;border-top:2px solid #111827;margin:24px 0"></div><p style="font-size:16px;line-height:1.8;color:#475569;margin:0">Discover the latest ${esc(brand())} pieces, selected for members of our private circle. Refined essentials, considered details, and a collection designed to be worn well.</p>${offer}<div style="text-align:center;margin:30px 0"><a href="${base()}/products" style="display:inline-block;background:#0b1220;color:#fff!important;text-decoration:none;padding:15px 30px;font:600 11px Arial,sans-serif;letter-spacing:1.8px;text-transform:uppercase">Explore the collection</a></div>${productGrid(liveProducts,currency)}</td></tr><tr><td style="padding:26px 32px;background:#111827;text-align:center"><div style="font:600 10px Arial,sans-serif;letter-spacing:2px;text-transform:uppercase;color:#e5e7eb">Client care · Secure shopping · Easy returns</div><div style="margin-top:16px;font:12px Arial,sans-serif;line-height:1.9"><a href="${base()}/support?tab=privacy" style="color:#fff;text-decoration:none">Privacy</a><span style="color:#64748b;padding:0 8px">·</span><a href="${base()}/support?tab=returns" style="color:#fff;text-decoration:none">Returns</a><span style="color:#64748b;padding:0 8px">·</span><a href="${base()}/support?tab=faq" style="color:#fff;text-decoration:none">FAQs</a></div><div style="margin-top:16px;color:#94a3b8;font:11px Arial,sans-serif">© 2026 ${esc(brand())}. All rights reserved.</div></td></tr></table></td></tr></table></body></html>`;
};
