import mongoose from "mongoose";
import { connectDB, SiteConfig } from "./_shared.js";
import { BRAND } from "../src/config/brand.js";
import { sendTransactionalMail } from "../src/utils/mail.js";
const getModel=(name:string)=>mongoose.models[name] as any;
const shortCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const shortTrackingNumber=()=>`DNF-${Math.floor(100000+Math.random()*900000)}`;
const shortOrderNumber=()=>`DNF-${new Date().getFullYear().toString().slice(-2)}${shortCode()}`;
const customerName=(order:any)=>String(order?.fullName||order?.shippingDetails?.firstName||order?.shippingAddress?.name||"Customer").trim()||"Customer";
const orderCurrency=(order:any)=>String(order?.currency||"USD").toUpperCase();
const validCurrency=(value:any)=>{const code=String(value||"").trim().toUpperCase();return /^[A-Z]{3}$/.test(code)?code:"";};
const configuredCurrency=async(requested:any)=>{const fallback=validCurrency(requested)||"USD";try{const config:any=await SiteConfig.findOne({key:"global"}).lean();const code=validCurrency(config?.currency||config?.currencyCode||config?.commerce?.currency||config?.localization?.currency);return code||fallback;}catch{return fallback;}};
const canonicalStatus=(value:any)=>{const raw=String(value||"").trim().toLowerCase().replace(/[_-]/g," ");const map:any={pending:"Pending",confirmed:"Confirmed",packed:"Packed","on the way":"On the Way",ontheway:"On the Way",shipped:"Shipped",delivered:"Delivered",cancelled:"Cancelled",canceled:"Cancelled"};return map[raw]||"";};
const normalizeTracking=(order:any)=>{const tracking={...(order?.tracking||{})};const history=Array.isArray(order?.statusHistory)?order.statusHistory:[];for(const item of history){const s=canonicalStatus(item?.status);const at=item?.at||item?.timestamp;if(s==="Confirmed"&&!tracking.confirmed)tracking.confirmed=at;if(s==="Packed"&&!tracking.packed)tracking.packed=at;if((s==="On the Way"||s==="Shipped")&&!tracking.shipped)tracking.shipped=at;if(s==="Delivered"&&!tracking.delivered)tracking.delivered=at;}return {...order,tracking};};
const getLiveProducts=async()=>{const Product=getModel("Product");if(!Product)return[];const rows=await Product.find({}).sort({isFeatured:-1,isNewArrival:-1,createdAt:-1}).limit(4).lean();return rows.map((p:any)=>({...p,id:String(p.id||p._id),name:p.name||p.title,image:p.image||p.images?.[0]||"",images:p.images||[],price:Number(p.price||0),currency:p.currency||"USD"}));};
export async function handleOrderRoutes(req:any,res:any):Promise<boolean>{
  const url=String(req.url||"").split("?")[0];const isAdminList=req.method==="GET"&&url==="/api/admin/orders";const isCreate=req.method==="POST"&&url==="/api/orders/create";const isStatus=req.method==="PUT"&&/^\/api\/admin\/orders\/[^/]+\/status$/.test(url);if(!isAdminList&&!isCreate&&!isStatus)return false;
  try{await connectDB();}catch(error){console.error("[orders] database unavailable",error);return res.status(503).json({success:false,error:"Database unavailable"});}
  const Order=getModel("Order");if(!Order)return res.status(503).json({success:false,error:"Order service unavailable"});
  try{
    if(isAdminList){const userId=String(req.query?.userId||"").trim();const email=String(req.query?.email||"").trim().toLowerCase();let filter:any={};if(userId){const User=getModel("User");const user=User?await User.findOne({uid:userId}).lean():null;filter=user?.email?{$or:[{userId},{email:String(user.email).toLowerCase()},{"shippingDetails.email":String(user.email).toLowerCase()}]}:{userId};}else if(email)filter={$or:[{email},{"shippingDetails.email":email}]};const orders=await Order.find(filter).sort({createdAt:-1}).lean();return res.status(200).json(orders.map(normalizeTracking));}
    if(isCreate){const body=req.body||{};const items=(Array.isArray(body.items)?body.items:[]).map((item:any)=>({...item,productId:String(item?.productId||item?.id||item?._id||''),quantity:Math.max(1,Number(item?.quantity||1)),price:Number(item?.price||0),subtotal:Number(item?.subtotal??(Number(item?.price||0)*Math.max(1,Number(item?.quantity||1))))}));const shippingDetails={...(body.shippingDetails||{}),firstName:body.shippingDetails?.firstName||body.fullName||body.shippingAddress?.fullName||"",lastName:body.shippingDetails?.lastName||"",email:body.shippingDetails?.email||body.email||"",phone:body.shippingDetails?.phone||body.phone||"",address:body.shippingDetails?.address||{}};const fullName=String(body.fullName||[shippingDetails.firstName,shippingDetails.lastName].filter(Boolean).join(" ")||"").trim();const email=String(shippingDetails.email||body.email||"").trim().toLowerCase();if(!items.length||items.some((item:any)=>!item.productId)||!fullName||!email)return res.status(400).json({success:false,error:"Missing customer name, email or valid order items"});const currency=await configuredCurrency(body.currency);const now=new Date();const orderNumber=String(body.orderNumber||shortOrderNumber());const trackingNumber=String(body.trackingNumber||shortTrackingNumber());const order=await Order.create({userId:String(body.userId||"GUEST"),items,totalAmount:Number(body.totalAmount||0),status:"Pending",currency,trackingNumber,shippingDetails,statusHistory:[{status:"Pending",at:now}]});await Order.collection.updateOne({_id:order._id},{$set:{orderNumber,email,fullName,phone:String(body.phone||shippingDetails.phone||""),shippingAddress:body.shippingAddress||shippingDetails.address,subtotal:Number(body.subtotal??body.totalAmount??0),discountAmount:Number(body.discountAmount||0),discountCode:String(body.discountCode||""),shippingCost:Number(body.shippingCost||0),paymentMethod:String(body.paymentMethod||"cod"),paymentStatus:String(body.paymentStatus||"pending"),tracking:{},updatedAt:new Date()}});const stored:any=await Order.collection.findOne({_id:order._id});try{const products=await getLiveProducts();const {getOrderEmail}=await import("../src/utils/AtelierEmails.js");await sendTransactionalMail(email,`${BRAND.name} | Order Confirmed`,getOrderEmail(customerName(stored),String(stored?.orderNumber||orderNumber),String(stored?.totalAmount||0),products,stored),`order:${order._id}:confirmed`);}catch(emailError){console.warn("[orders] confirmation email failed after order save",emailError);}return res.status(201).json({success:true,orderId:order._id,order:normalizeTracking(stored)});}
    const id=url.split("/")[4];if(!mongoose.isValidObjectId(id))return res.status(400).json({success:false,error:"Invalid order id"});const status=canonicalStatus(req.body?.status);if(!status)return res.status(400).json({success:false,error:"Invalid status"});const existing:any=await Order.findById(id);if(!existing)return res.status(404).json({success:false,error:"Order not found"});const existingRaw:any=await Order.collection.findOne({_id:existing._id});const changed=canonicalStatus(existing.status)!==status;existing.status=status;if(!existing.trackingNumber&&["Packed","On the Way","Shipped"].includes(status))existing.trackingNumber=shortTrackingNumber();if(changed){const now=new Date();existing.statusHistory=[...(existing.statusHistory||[]),{status,at:now}];}await existing.save();const rawTracking={...(existingRaw?.tracking||{})};const history=[...(existing.statusHistory||[])];if(status==="Confirmed")rawTracking.confirmed=history[history.length-1]?.at||new Date();if(status==="Packed")rawTracking.packed=history[history.length-1]?.at||new Date();if(status==="On the Way"||status==="Shipped")rawTracking.shipped=history[history.length-1]?.at||new Date();if(status==="Delivered")rawTracking.delivered=history[history.length-1]?.at||new Date();await Order.collection.updateOne({_id:existing._id},{$set:{tracking:rawTracking,orderNumber:existingRaw?.orderNumber||shortOrderNumber(),trackingNumber:existing.trackingNumber,updatedAt:new Date()}});const order:any=normalizeTracking(await Order.collection.findOne({_id:existing._id}));if(changed&&order.email){try{const products=await getLiveProducts();const {getStatusEmail}=await import("../src/utils/AtelierEmails.js");const currency=orderCurrency(order);const key=`order:${order._id}:${status.toLowerCase().replace(/\s+/g,"-")}`;const latestEvent=Array.isArray(order.statusHistory)&&order.statusHistory.length?order.statusHistory[order.statusHistory.length-1]?.at:order.updatedAt;const html=getStatusEmail(customerName(order),String(order.orderNumber||order._id),status,order.trackingNumber||"",Number(order.totalAmount||0),currency,products,latestEvent||new Date());await sendTransactionalMail(order.email,`${BRAND.name} | Order ${status}`,html,key);}catch(emailError){console.warn("[orders] status email failed after status update",emailError);}}return res.status(200).json({success:true,order});
  }catch(error){console.error("[orders] route failed",error);return res.status(500).json({success:false,error:"Order operation failed"});}
}
